PROGRAM	= opcodes2
SOURCES	= opcodes2.asm note_table.asm sound_engine.asm volume_envelopes.asm \
	sound_opcodes.asm \
	songs.asm song0.asm song1.asm song2.asm song3.asm song4.asm \
	song5.asm song6.asm song7.asm

CONFIG_FILE = nes.cfg

include ../../common.mk
